<?php
/**
 * Tasks to run during uninstallation of this plugin.
 *
 * @package next-meetup-hint
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// if uninstall.php is not called by WordPress, die.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	die;
}

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// delete our transient, if set.
delete_transient( 'next_meetup_hint' );

// delete settings on user profiles.
foreach ( get_users() as $user ) {
	// bail if user is not a user object.
	if ( ! $user instanceof WP_User ) {
		continue;
	}

	// delete the settings on this user.
	delete_user_meta( $user->ID, 'hide_next_meet_hint' );
	delete_user_meta( $user->ID, 'next_meet_hint_days' );
	delete_user_meta( $user->ID, 'hide_next_meetup_hint_for_2_days' );
}

// delete all settings.
\NextMeetupHint\Dependencies\easySettingsForWordPress\Settings::get_instance()->delete_settings();
